### ISSUE TITLE
Requesting for the missing csv files

### ISSUE THREAD

**Issue by ShimulAUST** [rezacsedu/DeepHateExplainer#1]
Hello Sir,
In your preprocess folder code there you have used multi_hate_data.csv and bengali_hate_v3.0.csv .But in input folder I can't find the csv files. It would be helpful for me if you update these files in input folder.

Thanks.

**Comment by rezacsedu** [comment]
@ShimulAUST, please refer to the [train.csv](https://raw.githubusercontent.com/rezacsedu/DeepHateExplainer/main/input/train.csv) file, as the multimodality was not used in the paper. In case of your interest in multimodality, you may refer to one of our recent papers "multimodal hate speech detection in Bengali" (link: https://arxiv.org/abs/2204.10196). 

**Disclaimer**: The data and lexicons contain contents that are racist, sexist, homophobic, and offensive in different ways. This dataset is collected and annotated only for research purposes. Besides, authors don’t take any liability if some statements contain very offensive and hateful statements that are either directed towards a specific person or entity or generalized towards a group. Please use it with your risk.
